### ISSUE TITLE
RuntimeError: Given groups=1, weight of size 64 1 5 5, expected input[1, 3, 256, 256] to have 1 channels, but got 3 channels instead

### ISSUE THREAD

**Issue by hadypranoto** [togheppi/DualGAN#1]
When i trying using 3 color image, i have an error like this

Traceback (most recent call last):
  File "c:/Users/hadypranoto/DualGAN/DualGAN_train.py", line 156, in <module>
    fake_B = G_A(real_A)
  File "C:\Users\hadypranoto\Anaconda3\envs\Tens\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\hadypranoto\DualGAN\model.py", line 71, in forward
    enc1 = self.conv1(x)
  File "C:\Users\hadypranoto\Anaconda3\envs\Tens\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\hadypranoto\DualGAN\model.py", line 17, in forward
    out = self.conv(x)
  File "C:\Users\hadypranoto\Anaconda3\envs\Tens\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\hadypranoto\Anaconda3\envs\Tens\lib\site-packages\torch\nn\modules\conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 64 1 5 5, expected input[1, 3, 256, 256] to have 1 channels, but got 3 channels instead

i think this is because the image, load as [3,256,256], but the conv process expect the input is [1, 3, 256, 256]

How can i fixed ith

**Comment by LeongDong** [comment]
expand_dims
